kind: Namespace
apiVersion: v1
metadata:
  name: {{namespace}}
spec: {}
status: {}

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller
  namespace: {{namespace}}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: {{namespace}}
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: {{namespace}}
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: {{namespace}}
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io